version: "2"
services:

  amqp:
    image: rabbitmq:3.6.5-management
    expose:
      - "5672" # RabbitMQ main port
      - "15672" # Management console (HTTP)
    ports:
      - "15672:15672"
    restart: always

  swift:
    image: vestaservices/swift-local:latest
    volumes:
      - /srv
    expose:
      - "8080"
    ports:
      - "8080:8080"

  mss:
    image: docker-registry.crim.ca/vesta/mss:1.7.0
    links:
      - amqp
      - swift
    ports:
      - "5170:5000"
    volumes:
      - ./mss/:/opt/mss_cfg/:ro
      - /data
    restart: always
    environment:
      VRP_CONFIGURATION: /opt/mss_cfg/conf.py

  transcoder:
    image: docker-registry.crim.ca/vesta/service-transcoding:0.2.8
    links:
      - amqp:amqp-server
      - mss
    user: "1000"
    restart: always

  sg:
    image: docker-registry.crim.ca/vesta/sg:1.7.3_old_build
    # image: vestaservices/servicegateway:1.7.6
    links:
      - amqp
    ports:
      - "5050:5000"
    volumes:
      - ./sg/:/opt/sg_cfg/:ro
      - /mnt/volume
    environment:
      VRP_CONFIGURATION: /opt/sg_cfg/conf.py
    logging:
      options:
        max-size: "100m"
    restart: always

  cb_server:
    build: ./callback_server/
    expose:
      - "5000"
    volumes:
      - ./callback_server/get_cb.py:/tmp/get_cb.py
    working_dir: /tmp
    command: /tmp/get_cb.py

  stub:
    image: vestaservices/servicestub:latest
    links:
      - amqp
      - mss
      - cb_server
    restart: always
    environment:
      C_FORCE_ROOT: "True"
    volumes:
      - ./celeryconfig.py:/conf/celeryconfig.py
    working_dir: /conf
    command: celery worker -A VestaService.stub -l INFO --config=celeryconfig -Q stub -n stub.%n

  flower:
    image: totem/celery-flower-docker
    links:
      - amqp
    user: "1000"
    restart: always
    ports:
      - "5555:5555"
    environment:
      AMQP_HOST: "amqp"
      AMQP_ADMIN_HOST: "amqp"
      FLOWER_BASIC_AUTH: "vesta:admin"

  jass:
    image: vestaservices/jass:latest
    environment:
      - MONGO_HOST=mongodb://annouser:whateve4rlogin@mongo/anno
    expose:
      - 5000
    ports:
      - "5002:5000"
    depends_on:
     - mongo

  mongo:
    image: tutum/mongodb
    expose:
      - 27017
      - 28017
    environment:
      - MONGODB_DATABASE=anno
      - MONGODB_USER=annouser
      - MONGODB_PASS=whateve4rlogin
    volumes:
      - /data

# For performance issues.
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
